steps:
  # =========================
  # Build & Push Backend
  # =========================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/scintiai-backend:$COMMIT_SHA',
        '-f',
        'Dockerfile.backend',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/scintiai-backend:$COMMIT_SHA'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', '${_BACKEND_SERVICE}',
        '--image', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/scintiai-backend:$COMMIT_SHA',
        '--region', '${_REGION}',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '8080'
      ]

  # =========================
  # Build & Push Frontend
  # =========================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/scintiai-frontend:$COMMIT_SHA',
        '-f',
        'Dockerfile.frontend',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/scintiai-frontend:$COMMIT_SHA'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', '${_FRONTEND_SERVICE}',
        '--image', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/scintiai-frontend:$COMMIT_SHA',
        '--region', '${_REGION}',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '8080'
      ]

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/scintiai-backend:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/scintiai-frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
