steps:
  # Build backend image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/backend:${COMMIT_SHA}
      - '-f'
      - Dockerfile.backend
      - .
    id: Build-Backend

  # Push backend image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/backend:${COMMIT_SHA}
    id: Push-Backend

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - backend-service
      - --image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/backend:${COMMIT_SHA}
      - --platform=managed
      - --region=${_DEPLOY_REGION}
      - --quiet
    id: Deploy-Backend

  # Build frontend image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/frontend:${COMMIT_SHA}
      - '-f'
      - Dockerfile.frontend
      - .
    id: Build-Frontend

  # Push frontend image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/frontend:${COMMIT_SHA}
    id: Push-Frontend

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - frontend-service
      - --image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/frontend:${COMMIT_SHA}
      - --platform=managed
      - --region=${_DEPLOY_REGION}
      - --quiet
    id: Deploy-Frontend

images:
  - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/backend:${COMMIT_SHA}
  - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/frontend:${COMMIT_SHA}

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_PROJECT_ID: qwiklabs-gcp-03-8a1eee3d23dc
  _DEPLOY_REGION: us-west1
  _AR_HOSTNAME: us-west1-docker.pkg.dev
  _AR_REPOSITORY: scintiai
  REPO_NAME: docker_scintiai
