version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: scintiai-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./test.db
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./backend:/app  

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: scintiai-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend